# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Employee.destroy_all
Employee.create!(name: "Trail Eloc", discord: "Trail#0174", role: 4)
Employee.create!(name: "Trey Jones", discord: "Pain#0195", role: 4)
Employee.create!(name: "Gabriel Rivera", discord: "alakna#4211", role: 3)
Employee.create!(name: "Jordan Adams", discord: "Hanad#9561", role: 3)
Employee.create!(name: "Huncho Brave", discord: "Xvedclout#9651", role: 3)
Employee.create!(name: "Jack Wallace", discord: "Avergen#3101", role: 3)
Employee.create!(name: "Tyler Killian", discord: "Tron#9435", role: 2)
Employee.create!(name: "Chad Stevens", discord: "ImMicrowaveable#5913", role: 2)
Employee.create!(name: "Habib Shadeed", discord: "Ashytoon#0001", role: 1)
Employee.create!(name: "Daquevious Williams", discord: "wassupmarcus#8767", role: 1)
Employee.create!(name: "Tyrone Blackmna", discord: "aggingothchik#4666", role: 1)
Employee.create!(name: "Lorenzo Wallace", discord: "Swaggnarok#6255", role: 0)
Employee.create!(name: "Everly Witchons", discord: "Vango#0867", role: 0)
Employee.create!(name: "Kaya Yui", discord: "Black#0670", role: 0)
Employee.create!(name: "Milan Bogatic", discord: "Milan#3971", role: 0)
Employee.create!(name: "Scott Wellsy", discord: "Wellsy#4074", role: 0)
Employee.create!(name: "Sandhills Bryan", discord: "Rebel#0125", role: 0)
Employee.create!(name: "James Kelley", discord: "warmth#4570", role: 0)
Employee.create!(name: "Timothy Beesley", discord: "PCSchmiet06#3260", role: 0)
Employee.create!(name: "Treyten Johnson", discord: "Quzurk#2183", role: 0)

Car.create!(name: "Elegy Retro Custom", price: 80000, rotation: true)
Car.create!(name: "Elegy", price: 64000, rotation: true)
Car.create!(name: "Jugular", price: 200000, rotation: true)
Car.create!(name: "NineF Cabrio", price: 150000, rotation: true)
Car.create!(name: "NineF", price: 130000, rotation: true)
Car.create!(name: "Alpha", price: 66000, rotation: true)
Car.create!(name: "Bullet", price: 175000, rotation: true)
Car.create!(name: "Benefactor Surano", price: 145000, rotation: true)
Car.create!(name: "Cyclone", price: 250000, rotation: true)
Car.create!(name: "Adder", price: 650000, rotation: true)
Car.create!(name: "FMJ", price: 312000, rotation: true)
Car.create!(name: "Entity XXR", price: 815000, rotation: true)
Car.create!(name: "Osiris", price: 495000, rotation: true)
Car.create!(name: "X-80 Proto", price: 975000, rotation: true)
Car.create!(name: "Vapid Sadler", price: 40000, rotation: true)
Car.create!(name: "BeeJay XL", price: 22000, rotation: true)
Car.create!(name: "Riata", price: 28000, rotation: true)
Car.create!(name: "SandKing", price: 50500, rotation: true)
Car.create!(name: "Patriot", price: 25000, rotation: true)
Car.create!(name: "Serrano", price: 35000, rotation: true)
Car.create!(name: "XLS", price: 45000, rotation: true)
Car.create!(name: "Dubsta Sport", price: 68000, rotation: true)
Car.create!(name: "Granger", price: 48000, rotation: true)
Car.create!(name: "Gauntlet", price: 42000, rotation: true)
Car.create!(name: "Impaler", price: 33000, rotation: true)
Car.create!(name: "Rat-Truck", price: 17500, rotation: true)
Car.create!(name: "Ruiner", price: 26000, rotation: true)
Car.create!(name: "SaberGT Custom", price: 49000, rotation: true)
Car.create!(name: "Stallion", price: 19000, rotation: true)
Car.create!(name: "Stirling GT", price: 185000, rotation: true)
Car.create!(name: "Mamba", price: 48000, rotation: true)
Car.create!(name: "Infernus Classic", price: 98000, rotation: true)
Car.create!(name: "Viseris", price: 72000, rotation: true)
Car.create!(name: "z190", price: 53000, rotation: true)
Car.create!(name: "Turismo Classic", price: 215000, rotation: true)
Car.create!(name: "Swinger", price: 58000, rotation: true)
Car.create!(name: "Oracle XS", price: 24000, rotation: true)
Car.create!(name: "Glendale", price: 16500, rotation: true)
Car.create!(name: "Stanier", price: 48000, rotation: true)
Car.create!(name: "Super Diamond", price: 145000, rotation: true)
Car.create!(name: "Warrener", price: 26000, rotation: true)
Car.create!(name: "Panto", price: 4500, rotation: true)
Car.create!(name: "Michelli GT", price: 14500, rotation: true)
Car.create!(name: "Issi", price: 10000, rotation: true)
Car.create!(name: "Prarie", price: 7500, rotation: true)
Car.create!(name: "Blista", price: 9500, rotation: true)
